<?php

use Illuminate\Database\Seeder;

class PermissionSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = [
            
            ['id' => 1, 'title' => 'user_management_access',],
            ['id' => 2, 'title' => 'permission_access',],
            ['id' => 3, 'title' => 'permission_create',],
            ['id' => 4, 'title' => 'permission_edit',],
            ['id' => 5, 'title' => 'permission_view',],
            ['id' => 6, 'title' => 'permission_delete',],
            ['id' => 7, 'title' => 'role_access',],
            ['id' => 8, 'title' => 'role_create',],
            ['id' => 9, 'title' => 'role_edit',],
            ['id' => 10, 'title' => 'role_view',],
            ['id' => 11, 'title' => 'role_delete',],
            ['id' => 12, 'title' => 'user_access',],
            ['id' => 13, 'title' => 'user_create',],
            ['id' => 14, 'title' => 'user_edit',],
            ['id' => 15, 'title' => 'user_view',],
            ['id' => 16, 'title' => 'user_delete',],
            ['id' => 17, 'title' => 'usernotification_access',],
            ['id' => 18, 'title' => 'usernotification_create',],
            ['id' => 19, 'title' => 'usernotification_edit',],
            ['id' => 20, 'title' => 'usernotification_view',],
            ['id' => 21, 'title' => 'usernotification_delete',],
            ['id' => 22, 'title' => 'country_access',],
            ['id' => 23, 'title' => 'country_create',],
            ['id' => 24, 'title' => 'country_edit',],
            ['id' => 25, 'title' => 'country_view',],
            ['id' => 26, 'title' => 'country_delete',],
            ['id' => 27, 'title' => 'state_access',],
            ['id' => 28, 'title' => 'state_create',],
            ['id' => 29, 'title' => 'state_edit',],
            ['id' => 30, 'title' => 'state_view',],
            ['id' => 31, 'title' => 'state_delete',],
            ['id' => 32, 'title' => 'city_access',],
            ['id' => 33, 'title' => 'city_create',],
            ['id' => 34, 'title' => 'city_edit',],
            ['id' => 35, 'title' => 'city_view',],
            ['id' => 36, 'title' => 'city_delete',],
            ['id' => 37, 'title' => 'countrydatum_access',],
            ['id' => 38, 'title' => 'countrydatum_create',],
            ['id' => 39, 'title' => 'countrydatum_edit',],
            ['id' => 40, 'title' => 'countrydatum_view',],
            ['id' => 41, 'title' => 'countrydatum_delete',],
            ['id' => 42, 'title' => 'citydatum_access',],
            ['id' => 43, 'title' => 'citydatum_create',],
            ['id' => 44, 'title' => 'citydatum_edit',],
            ['id' => 45, 'title' => 'citydatum_view',],
            ['id' => 46, 'title' => 'citydatum_delete',],
            ['id' => 47, 'title' => 'countrylanguage_access',],
            ['id' => 48, 'title' => 'countrylanguage_create',],
            ['id' => 49, 'title' => 'countrylanguage_edit',],
            ['id' => 50, 'title' => 'countrylanguage_view',],
            ['id' => 51, 'title' => 'countrylanguage_delete',],
            ['id' => 52, 'title' => 'question_access',],
            ['id' => 53, 'title' => 'question_create',],
            ['id' => 54, 'title' => 'question_edit',],
            ['id' => 55, 'title' => 'question_view',],
            ['id' => 56, 'title' => 'question_delete',],
            ['id' => 57, 'title' => 'personalityquestion_access',],
            ['id' => 58, 'title' => 'personalityquestion_create',],
            ['id' => 59, 'title' => 'personalityquestion_edit',],
            ['id' => 60, 'title' => 'personalityquestion_view',],
            ['id' => 61, 'title' => 'personalityquestion_delete',],
            ['id' => 62, 'title' => 'questionoption_access',],
            ['id' => 63, 'title' => 'questionoption_create',],
            ['id' => 64, 'title' => 'questionoption_edit',],
            ['id' => 65, 'title' => 'questionoption_view',],
            ['id' => 66, 'title' => 'questionoption_delete',],
            ['id' => 67, 'title' => 'personalityoption_access',],
            ['id' => 68, 'title' => 'personalityoption_create',],
            ['id' => 69, 'title' => 'personalityoption_edit',],
            ['id' => 70, 'title' => 'personalityoption_view',],
            ['id' => 71, 'title' => 'personalityoption_delete',],
            ['id' => 72, 'title' => 'answer_access',],
            ['id' => 73, 'title' => 'answer_create',],
            ['id' => 74, 'title' => 'answer_edit',],
            ['id' => 75, 'title' => 'answer_view',],
            ['id' => 76, 'title' => 'answer_delete',],
            ['id' => 77, 'title' => 'personalityanswer_access',],
            ['id' => 78, 'title' => 'personalityanswer_create',],
            ['id' => 79, 'title' => 'personalityanswer_edit',],
            ['id' => 80, 'title' => 'personalityanswer_view',],
            ['id' => 81, 'title' => 'personalityanswer_delete',],
            ['id' => 82, 'title' => 'message_access',],
            ['id' => 83, 'title' => 'message_create',],
            ['id' => 84, 'title' => 'message_edit',],
            ['id' => 85, 'title' => 'message_view',],
            ['id' => 86, 'title' => 'message_delete',],
            ['id' => 87, 'title' => 'messageconection_access',],
            ['id' => 88, 'title' => 'messageconection_create',],
            ['id' => 89, 'title' => 'messageconection_edit',],
            ['id' => 90, 'title' => 'messageconection_view',],
            ['id' => 91, 'title' => 'messageconection_delete',],
            ['id' => 92, 'title' => 'messagedelete_access',],
            ['id' => 93, 'title' => 'messagedelete_create',],
            ['id' => 94, 'title' => 'messagedelete_edit',],
            ['id' => 95, 'title' => 'messagedelete_view',],
            ['id' => 96, 'title' => 'messagedelete_delete',],
            ['id' => 97, 'title' => 'messageblock_access',],
            ['id' => 98, 'title' => 'messageblock_create',],
            ['id' => 99, 'title' => 'messageblock_edit',],
            ['id' => 100, 'title' => 'messageblock_view',],
            ['id' => 101, 'title' => 'messageblock_delete',],
            ['id' => 102, 'title' => 'whoviewme_access',],
            ['id' => 103, 'title' => 'whoviewme_create',],
            ['id' => 104, 'title' => 'whoviewme_edit',],
            ['id' => 105, 'title' => 'whoviewme_view',],
            ['id' => 106, 'title' => 'whoviewme_delete',],
            ['id' => 107, 'title' => 'usercommeetrequest_access',],
            ['id' => 108, 'title' => 'usercommeetrequest_create',],
            ['id' => 109, 'title' => 'usercommeetrequest_edit',],
            ['id' => 110, 'title' => 'usercommeetrequest_view',],
            ['id' => 111, 'title' => 'usercommeetrequest_delete',],
            ['id' => 112, 'title' => 'usergroupmap_access',],
            ['id' => 113, 'title' => 'usergroupmap_create',],
            ['id' => 114, 'title' => 'usergroupmap_edit',],
            ['id' => 115, 'title' => 'usergroupmap_view',],
            ['id' => 116, 'title' => 'usergroupmap_delete',],
            ['id' => 117, 'title' => 'groupsmember_access',],
            ['id' => 118, 'title' => 'groupsmember_create',],
            ['id' => 119, 'title' => 'groupsmember_edit',],
            ['id' => 120, 'title' => 'groupsmember_view',],
            ['id' => 121, 'title' => 'groupsmember_delete',],
            ['id' => 122, 'title' => 'usersession_access',],
            ['id' => 123, 'title' => 'usersession_create',],
            ['id' => 124, 'title' => 'usersession_edit',],
            ['id' => 125, 'title' => 'usersession_view',],
            ['id' => 126, 'title' => 'usersession_delete',],
            ['id' => 127, 'title' => 'redirectlink_access',],
            ['id' => 128, 'title' => 'redirectlink_create',],
            ['id' => 129, 'title' => 'redirectlink_edit',],
            ['id' => 130, 'title' => 'redirectlink_view',],
            ['id' => 131, 'title' => 'redirectlink_delete',],
            ['id' => 132, 'title' => 'weeklyhit_access',],
            ['id' => 133, 'title' => 'weeklyhit_create',],
            ['id' => 134, 'title' => 'weeklyhit_edit',],
            ['id' => 135, 'title' => 'weeklyhit_view',],
            ['id' => 136, 'title' => 'weeklyhit_delete',],
            ['id' => 137, 'title' => 'astrologycalcsign_access',],
            ['id' => 138, 'title' => 'astrologycalcsign_create',],
            ['id' => 139, 'title' => 'astrologycalcsign_edit',],
            ['id' => 140, 'title' => 'astrologycalcsign_view',],
            ['id' => 141, 'title' => 'astrologycalcsign_delete',],
            ['id' => 142, 'title' => 'payment_access',],
            ['id' => 143, 'title' => 'payment_create',],
            ['id' => 144, 'title' => 'payment_edit',],
            ['id' => 145, 'title' => 'payment_view',],
            ['id' => 146, 'title' => 'payment_delete',],
            ['id' => 147, 'title' => 'userspaymentsplan_access',],
            ['id' => 148, 'title' => 'userspaymentsplan_create',],
            ['id' => 149, 'title' => 'userspaymentsplan_edit',],
            ['id' => 150, 'title' => 'userspaymentsplan_view',],
            ['id' => 151, 'title' => 'userspaymentsplan_delete',],
            ['id' => 152, 'title' => 'blockuser_access',],
            ['id' => 153, 'title' => 'blockuser_create',],
            ['id' => 154, 'title' => 'blockuser_edit',],
            ['id' => 155, 'title' => 'blockuser_view',],
            ['id' => 156, 'title' => 'blockuser_delete',],
            ['id' => 157, 'title' => 'subscriptionplan_access',],
            ['id' => 158, 'title' => 'subscriptionplan_create',],
            ['id' => 159, 'title' => 'subscriptionplan_edit',],
            ['id' => 160, 'title' => 'subscriptionplan_view',],
            ['id' => 161, 'title' => 'subscriptionplan_delete',],
            ['id' => 162, 'title' => 'astrologycalc_access',],
            ['id' => 163, 'title' => 'astrologycalc_create',],
            ['id' => 164, 'title' => 'astrologycalc_edit',],
            ['id' => 165, 'title' => 'astrologycalc_view',],
            ['id' => 166, 'title' => 'astrologycalc_delete',],
            ['id' => 167, 'title' => 'uservideo_access',],
            ['id' => 168, 'title' => 'uservideo_create',],
            ['id' => 169, 'title' => 'uservideo_edit',],
            ['id' => 170, 'title' => 'uservideo_view',],
            ['id' => 171, 'title' => 'uservideo_delete',],

        ];

        foreach ($items as $item) {
            \App\Permission::create($item);
        }
    }
}
