<?php

$factory->define(App\User::class, function (Faker\Generator $faker) {
    return [
        "name" => $faker->name,
        "email" => $faker->safeEmail,
        "password" => str_random(10),
        "remember_token" => $faker->name,
        "matchstatus" => $faker->name,
        "customer_id" => $faker->name,
        "status" => $faker->name,
        "cancelmembership" => $faker->name,
        "unsubscribeemail" => $faker->name,
        "usersubscribe" => $faker->name,
        "shareedit" => $faker->name,
        "sharetime" => $faker->name,
        "block" => $faker->name,
        "sendemail" => $faker->name,
        "lastvisitdate" => $faker->name,
        "activation" => $faker->name,
        "params" => $faker->name,
        "lastresettime" => $faker->name,
        "resetcount" => $faker->name,
        "otpkey" => $faker->name,
        "otep" => $faker->name,
        "requirereset" => $faker->name,
        "lookingfor" => collect(["Male","Female",])->random(),
        "ethnicity" => $faker->name,
        "country_id" => factory('App\Country')->create(),
        "state_id" => factory('App\State')->create(),
        "city_id" => factory('App\City')->create(),
        "gender" => collect(["Male","Female","Other",])->random(),
        "personality" => $faker->name,
        "aboutme" => $faker->name,
        "dob" => $faker->date("d-m-Y", $max = 'now'),
        "devicetype" => $faker->name,
        "devicetoken" => $faker->name,
        "facebookid" => $faker->name,
        "gmailid" => $faker->name,
        "ntcount" => $faker->name,
    ];
});
